version: 0.2

phases:
  install:
    runtime-versions:
      flutter: 3.13.1
  build:
    commands:
      - flutter pub get
      - flutter build web --release
artifacts:
  files:
    - '**/*'
  base-directory: build/web